on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: remdub/hw-composite-action@v0.1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: |
          for i in {1..10}
          do
            echo step $i
            echo random-number "$RANDOM_NUMBER"
            sleep 10
          done
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}